name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: 'test'
          POSTGRES_PASSWORD: 'password'
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Migrate PostgreSQL
      run: make migrate

    - name: Install SQLBoiler
      run: make install-sqlboiler

    - name: Generate SQLBoiler
      run: make generate-sqlboiler

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...
